// Demo carrier database for softdrop
export type Carrier = {
  carrier_id: string;
  carrier_name: string;
  carrier_type: string;
  carrier_phone: string;
  carrier_photo_url: string;
  carrier_online: boolean;
  latitude?: number;
  longitude?: number;
};

export const carrierDatabase: Carrier[] = [
  {
    carrier_id: "walk1",
    carrier_name: "John Walker",
    carrier_type: "walk",
    carrier_phone: "+2348010000001",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/1.jpg",
    carrier_online: true,
    latitude: 6.6018 + Math.random() * 0.02,
    longitude: 3.3515 + Math.random() * 0.02,
  },
  {
    carrier_id: "walk2",
    carrier_name: "Jane Walker",
    carrier_type: "walk",
    carrier_phone: "+2348010000002",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/2.jpg",
    carrier_online: true,
    latitude: 6.6372 + Math.random() * 0.02,
    longitude: 3.3746 + Math.random() * 0.02,
  },
  {
    carrier_id: "bicycle1",
    carrier_name: "Mike Cyclist",
    carrier_type: "bicycle",
    carrier_phone: "+2348010000003",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/3.jpg",
    carrier_online: true,
    latitude: 6.6206 + Math.random() * 0.02,
    longitude: 3.3244 + Math.random() * 0.02,
  },
  {
    carrier_id: "bicycle2",
    carrier_name: "Anna Cyclist",
    carrier_type: "bicycle",
    carrier_phone: "+2348010000004",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/4.jpg",
    carrier_online: true,
    latitude: 6.6346 + Math.random() * 0.02,
    longitude: 3.3376 + Math.random() * 0.02,
  },
  {
    carrier_id: "bike1",
    carrier_name: "Sam Biker",
    carrier_type: "bike",
    carrier_phone: "+2348010000005",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/5.jpg",
    carrier_online: true,
    latitude: 6.6018 + Math.random() * 0.02,
    longitude: 3.3515 + Math.random() * 0.02,
  },
  {
    carrier_id: "bike2",
    carrier_name: "Lisa Biker",
    carrier_type: "bike",
    carrier_phone: "+2348010000006",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/6.jpg",
    carrier_online: true,
    latitude: 6.6372 + Math.random() * 0.02,
    longitude: 3.3746 + Math.random() * 0.02,
  },
  {
    carrier_id: "car1",
    carrier_name: "Tom Driver",
    carrier_type: "car",
    carrier_phone: "+2348010000007",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/7.jpg",
    carrier_online: true,
    latitude: 6.6206 + Math.random() * 0.02,
    longitude: 3.3244 + Math.random() * 0.02,
  },
  {
    carrier_id: "car2",
    carrier_name: "Sara Driver",
    carrier_type: "car",
    carrier_phone: "+2348010000008",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/8.jpg",
    carrier_online: false,
  },
  {
    carrier_id: "walk3",
    carrier_name: "Chris Walker",
    carrier_type: "walk",
    carrier_phone: "+2348010000009",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/9.jpg",
    carrier_online: true,
    latitude: 6.6346 + Math.random() * 0.02,
    longitude: 3.3376 + Math.random() * 0.02,
  },
  {
    carrier_id: "bicycle3",
    carrier_name: "Nina Cyclist",
    carrier_type: "bicycle",
    carrier_phone: "+2348010000010",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/10.jpg",
    carrier_online: false,
  },
  {
    carrier_id: "bike3",
    carrier_name: "Alex Biker",
    carrier_type: "bike",
    carrier_phone: "+2348010000011",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/11.jpg",
    carrier_online: true,
    latitude: 6.6018 + Math.random() * 0.02,
    longitude: 3.3515 + Math.random() * 0.02,
  },
  {
    carrier_id: "car3",
    carrier_name: "Eva Driver",
    carrier_type: "car",
    carrier_phone: "+2348010000012",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/12.jpg",
    carrier_online: true,
    latitude: 6.6372 + Math.random() * 0.02,
    longitude: 3.3746 + Math.random() * 0.02,
  },
  {
    carrier_id: "walk4",
    carrier_name: "Peter Walker",
    carrier_type: "walk",
    carrier_phone: "+2348010000013",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/13.jpg",
    carrier_online: true,
  },
  {
    carrier_id: "bicycle4",
    carrier_name: "Olga Cyclist",
    carrier_type: "bicycle",
    carrier_phone: "+2348010000014",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/14.jpg",
    carrier_online: true,
    latitude: 6.6206 + Math.random() * 0.02,
    longitude: 3.3244 + Math.random() * 0.02,
  },
  {
    carrier_id: "bike4",
    carrier_name: "Victor Biker",
    carrier_type: "bike",
    carrier_phone: "+2348010000015",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/15.jpg",
    carrier_online: true,
    latitude: 6.6346 + Math.random() * 0.02,
    longitude: 3.3376 + Math.random() * 0.02,
  },
  {
    carrier_id: "car4",
    carrier_name: "Maya Driver",
    carrier_type: "car",
    carrier_phone: "+2348010000016",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/16.jpg",
    carrier_online: false,
  },
  {
    carrier_id: "walk5",
    carrier_name: "Steve Walker",
    carrier_type: "walk",
    carrier_phone: "+2348010000017",
    carrier_photo_url: "https://randomuser.me/api/portraits/men/17.jpg",
    carrier_online: true,
    latitude: 6.6018 + Math.random() * 0.02,
    longitude: 3.3515 + Math.random() * 0.02,
  },
  {
    carrier_id: "car5",
    carrier_name: "Linda Driver",
    carrier_type: "car",
    carrier_phone: "+2348010000018",
    carrier_photo_url: "https://randomuser.me/api/portraits/women/18.jpg",
    carrier_online: true,
    latitude: 6.6372 + Math.random() * 0.02,
    longitude: 3.3746 + Math.random() * 0.02,
  },
];
